# Generated by Django 5.0.1 on 2024-01-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
    ]
